
version: '3.5'
services:
  database:
    build: ./database
    networks:
      - network2
  backend:
    build: ./backend    
    networks:
      - network1
      - network2
    depends_on:
      - database
  proxy:
    build: ./nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./html:/etc/nginx/html
    - ./certs:/etc/nginx/ssl
    networks:
      - network1
    ports:
      - "443:443"
    depends_on:
      - backend
networks:
  network1:
  network2:
