
version: '3.5'
services:

  backend:
    build: ./backend
    ports:
      - 8000:80

  database:
    build: ./database
    ports:
      - 8080:8080

  proxy:
    build: ./nginx
    ports:
      - 80

volumes:
  backend: