
version: '3.5'
services:
  database:
    build: ./database
    networks:
      - network2
  backend:
    build: ./backend    
    networks:
      - network1
      - network2
    depends_on:
      - database
  proxy:
    build: ./nginx
    networks:
      - network1
    ports:
      - "443:443"
    depends_on:
      - backend
networks:
  network1:
  network2:
