
version: '3.5'
services:
  database:
    build: ./database
    networks:
      - network2
  backend:
    build: ./backend    
    networks:
      - network1
      - network2
    depends_on:
      - database
  proxy:
    build: ./nginx
    volumes:
    - ./html:/etc/nginx/html
    - ./certs/site.key:/etc/nginx/ssl/ssl/site.key
    - ./certs/site.crt:/etc/nginx/ssl/site.key
    - ./certs/rootCA.pem:/etc/nginx/ssl/rootCA.pem
    - /nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - network1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
networks:
  network1:
  network2:
