
version: '3.5'
services:

  backend:
    build: ./backend
    networks:
      - network1
      - network2

  database:
    build: ./database
    networks:
      - network2
    ports:
      - 8080:8080

  proxy:
    build: ./nginx
    networks:
      - network1

volumes:
  backend: