
version: '3.5'
services:
  database:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - network2
  backend:
    build: ./backend    
    networks:
      - network1
      - network2
    depends_on:
      - database
    ports:
      - "8080:80"
  proxy:
    build: ./nginx
    networks:
      - network1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
networks:
  network1:
  network2:
